# Mid EXAM : Tools and Techniques Data Science 

# Task 1: ( 5 Marks)  Warp up 

# Note : Rename the file with your name and id and also mention your name and id inside here 

#### Name: <b>Nouman Akram</b>                                ID: <b>S2023393004</b>

In [37]:
# Q1. Here, we take each element in the list a (temporarily assigning it the value i) 
a = [5, 10, 15, 20]

In [28]:
# (i)	Find the square each element in the list. This creates a new list called b and does not modify a through data comprehension.

In [29]:
b = list(map(lambda x: x** 2, a))

In [30]:
b

[25, 100, 225, 400]

In [31]:
# (ii)	Write a conditional statement of only squaring the elements if the element is not equal to 10


In [192]:
filter_list = list(map(lambda x: x * x if x != 10 else x, a))

In [193]:
filter_list

[25, 10, 225, 400]

In [33]:
# Q2. (i) Write the command of random samples from a uniform distribution between 0 and 1? 

In [40]:
import numpy as np

In [86]:
random_uniform = np.random.uniform(0, 1, size=(5, 3))

In [87]:
random_uniform

array([[0.49538707, 0.92078917, 0.22234652],
       [0.86206678, 0.36950275, 0.93442589],
       [0.02428641, 0.04477349, 0.3365527 ],
       [0.03095546, 0.23782688, 0.42523262],
       [0.73819806, 0.89131175, 0.73094333]])

In [75]:
#(ii)	Write the command to slice the column 1? 

In [89]:
random_uniform[:, 1]

array([0.92078917, 0.36950275, 0.04477349, 0.23782688, 0.89131175])

In [77]:
#(iii)	Write the command of first and third elements in column 1?

In [100]:
random_uniform[:, 1][1:4:2]

array([0.36950275, 0.23782688])

In [81]:
#(iv)	 Write the command of returns an 8 x 4 array

In [83]:
zero_arry = np.zeros((8,4))

In [85]:
zero_arry

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
zero_arry.shape

(8, 4)

In [94]:
import pandas as pd 

In [23]:
#Q3. Create a Series that looks like this below:
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [98]:
index = ["Flour", "Milk", "Eggs", "Spam"]
element = ["4 cups", "1 cup", "2 large", "1 can"]
pd.Series(element, index=index, name="Dinner")

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [25]:
# Q  4 Create the Data frame  as th output[27]

In [113]:
data = {"Apples": [35, 41], "Bananas": [21, 34]}
df = pd.DataFrame(data, index=["2017Sales", "2018Sales"])

In [114]:
df

Apples  Bananas
2017Sales      35       21
2018Sales      41       34

In [28]:
#Q4. create Dataframe then find imputation for these missing NaN in the out[47]

In [175]:
data = {
    "Age": [23,  39, 45, np.NaN],
    "Gender": ["M", "F", "F", "M"],
    "Income": [24200.0, np.NaN, 45390.0, np.NaN],
    "Religion": ["Muslim", "chirstian", np.NaN, "Muslim"]
}
        

In [176]:
df = pd.DataFrame(data)

In [177]:
df

Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F      NaN  chirstian
2  45.0      F  45390.0        NaN
3   NaN      M      NaN     Muslim

In [178]:
df

Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F      NaN  chirstian
2  45.0      F  45390.0        NaN
3   NaN      M      NaN     Muslim

In [148]:
#Q4(i)	Compute the appropriate missing value in income attribute?

In [182]:
df["Income"].mean()

34795.0

In [151]:
#(ii)	Compute the appropriate missing values in religion attribute? 

In [184]:
df["Religion"].mode()[0]

'Muslim'

In [154]:
#(iii)	Drop the columns where any of the elements is nan

In [186]:
drop_column = df.dropna(axis=1)

In [187]:
drop_column

Gender
0      M
1      F
2      F
3      M

In [172]:
#(iv)	Keep only the rows with at least 2 non-na values

In [191]:
df.dropna(thresh=2)

Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F      NaN  chirstian
2  45.0      F  45390.0        NaN
3   NaN      M      NaN     Muslim